### PR TITLE
I have completed task today and filename of Example2 -commit01

### PR DESCRIPTION
**Pull request by sureshbabuk9912**
Hi TL,
I have completed Example02 file please check and review

Regards,
Member22

### CODE REVIEW

**Comment by KASB99123** [comment]
Hi Member22,
your code is looks fine, but add  extra data  please..

Regards,
TL

**Comment by sureshbabuk9912** [comment]
Hi Tl,
I have added changes inside ,please look once and review..

Regards,
Member22

**Comment by KASB99123** [comment]
Hi Member22,
now your code looks fine, please  do merge .

**Comment by sureshbabuk9912** [comment]
Hi TL, 
I have merged Example2 file into master.

**Pull request merged**
